image: docker:latest
services:
  - docker:dind
stages:
- build
variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG --no-cache=true .
    - docker push $IMAGE_TAG
  tags:
    - shell
